sudo: false
language: generic

addons:
  apt:
    packages:
      - smlnj
      - libcml-smlnj
      - libcmlutil-smlnj
      - libsmlnj-smlnj

before_install:
  - git clone https://github.com/MLton/mlton MLton/mlton
  - cd MLton/mlton
  - make all
  - make install

script:
- mlton -output n2o.exe n2o.mlb
- ml-build n2o.cm Main.main n2o.nj
