# sudo: false
language: generic

addons:
  apt:
    packages:
      # - mlton
      - smlnj
      - libcml-smlnj
      - libcmlutil-smlnj
      - libsmlnj-smlnj
      - wget
      
before_install:
- wget https://github.com/MLton/mlton/releases/download/on-20180207-release/mlton-20180207-1.amd64-linux.tgz
- tar -xzf mlton-20180207-1.amd64-linux.tgz
- mv mlton-20180207-1.amd64-linux $HOME/.mlton
- export PATH=$HOME/.mlton/bin:$PATH
 
script:
- mlton
- mlton -output n2o.exe n2o.mlb
- ml-build n2o.cm Main.main n2o.nj
